imports:
    - { resource: '@VSApplicationInstalatorBundle/Resources/config/app/fixtures/application_configuration.yaml' }
    
    - { resource: '@VSCatalogBundle/Resources/config/app/fixtures/application_configuration.yaml' }
    - { resource: '@VSCatalogBundle/Resources/config/app/fixtures/catalog_configuration.yaml' }
    
    #- { resource: '@VSApplicationInstalatorBundle/Resources/config/app/fixtures/sample_data.yaml' }
    - { resource: '@VSCatalogBundle/Resources/config/app/fixtures/subscription_sample_data.yaml' }
    - { resource: '@VSCatalogBundle/Resources/config/app/fixtures/payment_sample_data.yaml' }
    - { resource: '@VSCatalogBundle/Resources/config/app/fixtures/catalog_sample_data.yaml' }

sylius_fixtures:
    suites:                
        vankosoft_sampledata_suite:
            fixtures:
                #test_countries: ~

